### ISSUE TITLE
TAD activity

### ISSUE THREAD

**Issue by francisfa** [NYU-BFX/hic-bench#16]
Hi, there are some questions:
1. I do not find that how do you define TAD activity and how do you calculate the TAD activity expression? There is no RNA-seq expression data. 
2. The `find-consistent-domains.pl` can generate the sample1 specific TAD files, sample2 specific and common TAD files. And then you use this different type TAD domain to calculate the TAD activity and TAD activity expression?

Thank you.

**Comment by javrodriguez** [comment]
Hi Francisfa,

There is no such TAD activity expression. It only computes the intra TAD activity per sample and computes the intra TAD activity fold-change and significance values between these samples. You can find more info and how to run a test data set here: 

https://github.com/NYU-BFX/hic-bench/wiki/Test-data:-domains-diff

**Comment by francisfa** [comment]
Yes, thank you for your reply.

What I understand the TAD activity is the average value of intra-TAD interaction frequency.

Thanks.
