### ISSUE TITLE
alignment statistic percentage plot still over 100%

### ISSUE THREAD

**Issue by gongyixiao** [NYU-BFX/hic-bench#3]
Here is one of the example:

/ifs/home/gongy05/.../ATAC-seq/pipeline/align-stats/results/align-stats.standard/align.by_sample.bowtie2/all-samples/alignment_barplots.pdf

**Comment by igordot** [comment]
I think this is actually fixed now.

**Comment by stevekm** [comment]
We need to track the commit that fixed it

**Comment by gongyixiao** [comment]
here it is:

bcd535186f383c6d71bdd3e3d266e771b0a64347

**Comment by stevekm** [comment]
Thanks Yixiao. When you make a commit that fixes and Issue, it will automatically get linked on here if you include "Fix #3" in the git commit message, where "#3" is the issue number at the top of the page. Also helps if the commit is done separately from other changes.

**Comment by gongyixiao** [comment]
great! nice feature to know. 

thanks Stephen.

Sincerely,
Yixiao Gong
