### ISSUE TITLE
how to set the params.tcsh file

### ISSUE THREAD

**Issue by liufuyan2016** [NYU-BFX/hic-bench#9]
Dear professor,
when I set my params.tcsh file ,the erro below is occured. I do not know how to set the line in module load .
########################################
$cat inputs/params/params.tcsh
#!/bin/tcsh

#unload
module unload samtools
module unload java
module unload gcc
module unload python
module unload r

#load basic tools
#module load python/2.7.3
**module load /share/nas2/genome/biosoft/samtools/1.3.1/
module load /share/nas2/genome/biosoft/bedtools/2.17.0/
module load /share/nas2/genome/biosoft/java/jdk/1.8.0_31/
module load /share/nas2/genome/biosoft/R/3.2.2/**
######################################
note: the softwares position in my computer is located in share/nas2/genome/biosoft/samtools/1.3.1/,
/share/nas2/genome/biosoft/bedtools/2.17.0/,/share/nas2/genome/biosoft/java/jdk/1.8.0_31/,/share/nas2/genome/biosoft/R/3.2.2/

报错信息：
ModuleCmd_Load.c(208):ERROR:105: Unable to locate a modulefile for '/share/nas2/genome/biosoft/samtools/1.3.1'
ModuleCmd_Load.c(208):ERROR:105: Unable to locate a modulefile for '/share/nas2/genome/biosoft/bedtools/2.17.0'
ModuleCmd_Load.c(208):ERROR:105: Unable to locate a modulefile for '/share/nas2/genome/biosoft/java/jdk/1.8.0_31'
ModuleCmd_Load.c(208):ERROR:105: Unable to locate a modulefile for '/share/nas2/genome/biosoft/R/3.2.2'

**Comment by tsirigos** [comment]
How about this?
module load samtools/1.3.1
